### ISSUE TITLE
JS issues

### ISSUE THREAD

**Issue by wrdana** [nathalie1226/paint#2]
![image](https://cloud.githubusercontent.com/assets/6061907/16467233/12ac66ba-3e4f-11e6-9378-67c909cd22ae.png)
- Clear button doesn't work
- When I just click - it doesn't work
- The code structure is rather messy: better names for variables,  order in the code, using functions and so on

**Comment by nathalie1226** [comment]
can you help me understand how to better structure it?

**Comment by nathalie1226** [comment]
i went over the js and changed the place of function created a big function that generates all the buttons and a few other changes
if there are other tricks i would love to learn them
